name: Python
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
permissions: {}
jobs:
    Test:
        # runs-on: ubuntu-latest
        strategy:
          fail-fast: true
          matrix:
            os: [macos-latest, ubuntu-latest, windows-latest]
            python-version: ['3.10', '3.11', '3.12']
            # toolchain: [beta, stable]
            toolchain: [stable]
        runs-on: ${{ matrix.os }}
        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Set up Python
            uses: actions/setup-python@v5
            with:
              # python-version: 3.12
              python-version: ${{ matrix.python-version }}

          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              pip install .

          - name: Run tests
            run: |
              pytest tests/
